apiVersion: apps/v1
kind: Deployment
metadata:
  name: hap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hap
  template:
    metadata:
      labels:
        app: hap
    spec:
      containers:
      - image: okteto.dev/hap:latest
        name: hap
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "7dc53f1a-e453-400c-adf7-adaf022e166a"
        - name: Vless_Path
          value: "/thdwzvnmsagjhpyttrewer"
        - name: Vmess_UUID
          value: "7dc53f1a-e453-400c-adf7-adaf022e166a"
        - name: Vmess_Path
          value: "/xhsubwtiewrghjvciotyzixg"
        - name: Share_Path
          value: "/v2link"
